NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.

For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, 
because it has one axis. That axis has a length of 3. 
In the example pictured below, the array has rank 2 (it is 2-dimensional). 
The first dimension (axis) has a length of 2, the second dimension has a length of 3.

[[ 1., 0., 0.],
 [ 0., 1., 2.]]

NumPy’s array class is called ndarray. 
It is also known by the alias array. 
Note that numpy.array is not the same as the Standard Python Library class array.array, 
which only handles one-dimensional arrays and offers less functionality. 
The more important attributes of an ndarray object are:

In [9]:
import numpy as np
a = np.arange(15).reshape(5, 3)
a




array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

ndarray.shape

the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.

In [7]:
a.shape


(5, 3)

ndarray.ndim

the number of axes (dimensions) of the array. 
In the Python world, the number of dimensions is referred to as rank.

In [4]:
a.ndim

2

ndarray.dtype

an object describing the type of the elements in the array. 
One can create or specify dtype’s using standard Python types. 
Additionally NumPy provides types of its own. numpy.int32, numpy.int16, 
and numpy.float64 are some examples.

In [5]:
a.dtype.name

'int32'

In [30]:
type(a)


numpy.ndarray

ndarray.itemsize

the size in bytes of each element of the array.
For example, an array of elements of type float64 has itemsize 8 (=64/8),
while one of type complex32 has itemsize 4 (=32/8).
It is equivalent to ndarray.dtype.itemsize.

In [31]:
a.itemsize

8

ndarray.size
the total number of elements of the array. 
This is equal to the product of the elements of shape.

In [32]:
a.size

15

In [33]:
type(a)

numpy.ndarray

In [7]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [8]:
type(b)

numpy.ndarray

In [10]:
b.ndim

1

ndarray.data
the buffer containing the actual elements of the array. 
Normally, we won’t need to use this attribute because 
we will access the elements in an array using indexing facilities.

# Array Creation

There are several ways to create arrays.

For example, you can create an array from a regular 
Python list or tuple using the array function. 
The type of the resulting array is deduced from 
the type of the elements in the sequences.

In [44]:
a = np.array([2,3,4])
a


array([2, 3, 4])

In [45]:
a.dtype

dtype('int64')

In [46]:
b = np.array([1.2, 3.5, 5.1])


In [47]:
b.dtype

dtype('float64')

A frequent error consists in calling array with multiple numeric arguments,
rather than providing a single list of numbers as an argument.

In [49]:
#a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT
a

array([1, 2, 3, 4])

array transforms sequences of sequences into two-dimensional arrays, 
sequences of sequences of sequences into three-dimensional arrays, and so on.

In [57]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [43]:
b = np.array([[1.5,2,3], [4,5,6]])
b
              


array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

The type of the array can also be explicitly specified at creation time:

In [53]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c


array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [62]:
np.zeros( (3,4) )


dtype('float64')

In [63]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [5]:
np.empty( (2,3) )                                 # uninitialized, output may vary


array([[1.e-323, 0.e+000, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000]])

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

In [6]:
np.arange( 10, 30, 5 )
#np.arange( 1, 30, 2 )


array([10, 15, 20, 25])

In [7]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [8]:
from numpy import pi
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)


In [9]:
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

    the last axis is printed from left to right,
    the second-to-last is printed from top to bottom,
    the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [10]:
a = np.arange(6)                         # 1d array
print(a)

[0 1 2 3 4 5]


In [11]:
b = np.arange(12).reshape(4,3)           # 2d array
print(b)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [164]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [165]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [166]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.

In [29]:
np.set_printoptions(threshold=100)

In [30]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [31]:
np.set_printoptions(threshold=100)

In [32]:
print(np.arange(100).reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# Basic Operations

In [33]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b



array([0, 1, 2, 3])

In [34]:
c = a-b
c


array([20, 29, 38, 47])

In [35]:

b**2



array([0, 1, 4, 9], dtype=int32)

In [36]:
10*np.sin(a)



array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [37]:
a<35

array([ True,  True, False, False])

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function or method:

In [40]:
A = np.array( [[1,1],
            [0,1]] )
B = np.array( [[2,0],
            [3,4]] )
A*B                         # elementwise product

array([[2, 0],
       [0, 4]])

In [41]:
A.dot(B)                    # matrix product

array([[5, 4],
       [3, 4]])

In [42]:
np.dot(A, B)                # another matrix product

array([[5, 4],
       [3, 4]])

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [43]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
print(a)
print(b)




[[3 3 3]
 [3 3 3]]
[[0.12631779 0.90953564 0.77225727]
 [0.29117445 0.55419475 0.97089697]]


In [180]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [181]:
a *= 3
print(a)


[[9 9 9]
 [9 9 9]]


In [182]:
b += a
b



array([[ 9.81676091,  9.76157799,  9.76812   ],
       [ 9.08176443,  9.86714016,  9.18714787]])

In [44]:

a += b               # b is not automatically converted to integer type


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [184]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

c = a+b
c


array([ 1.        ,  2.57079633,  4.14159265])

In [186]:
c.dtype.name


'float64'

In [188]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [190]:
d.dtype.name

'complex128'

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [194]:
a = np.random.random((2,3))
a


array([[ 0.87160954,  0.75751359,  0.47334202],
       [ 0.22142611,  0.52991767,  0.02161312]])

In [195]:
a.sum()

2.8754220451916699

In [196]:
a.min()

0.021613116950644051

In [197]:
a.max()


0.87160954269538127

# Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [210]:
B = np.arange(3)
B


array([0, 1, 2])

In [213]:
np.exp(B)



array([ 1.        ,  2.71828183,  7.3890561 ])

In [212]:
np.sqrt(B)



array([ 0.        ,  1.        ,  1.41421356])

In [214]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([ 2.,  0.,  6.])

# Indexing, Slicing and Iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [216]:
a = np.arange(10)**3
a




array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [219]:
a[2]

8

In [229]:
a[:6:2]


array([ 0,  8, 64])

In [230]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [231]:
a[ : :-1]                      # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [232]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [234]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b



array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [235]:
b[2,3]

23

In [238]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [239]:
b[ : ,1]                        # equivalent to the previous example


array([ 1, 11, 21, 31, 41])

In [240]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [ ]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

# Shape Manipulation

An array has a shape given by the number of elements along each axis:

In [241]:
a = np.floor(10*np.random.random((3,4)))
a


array([[ 1.,  4.,  2.,  1.],
       [ 0.,  9.,  4.,  2.],
       [ 7.,  0.,  5.,  3.]])

In [242]:
a.shape


(3, 4)

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [45]:
a.ravel()  # both flatten and ravel returns the array, flattened.difference between them are 
a.flatten#eg:b2 = a.ravel()  
#b2[0] = 101  # changing b2 changes a also but flatten wont change parent class


<function ndarray.flatten>

In [246]:
a.reshape(6,2)  # returns the array with a modified shape


array([[ 1.,  4.],
       [ 2.,  1.],
       [ 0.,  9.],
       [ 4.,  2.],
       [ 7.,  0.],
       [ 5.,  3.]])

In [247]:

a.T  # returns the array, transposed


array([[ 1.,  0.,  7.],
       [ 4.,  9.,  0.],
       [ 2.,  4.,  5.],
       [ 1.,  2.,  3.]])

In [250]:

a.T.shape


(4, 3)

In [251]:

a.shape

(3, 4)

# Splitting one array into several smaller ones

In [46]:
a = np.floor(10*np.random.random((2,6)))
a

array([[4., 5., 2., 0., 8., 9.],
       [5., 2., 0., 5., 7., 6.]])

In [48]:
np.hsplit(a,3)

[array([[4., 5.],
        [5., 2.]]), array([[2., 0.],
        [0., 5.]]), array([[8., 9.],
        [7., 6.]])]

In [50]:
np.hsplit(a,3)[1]   

array([[2., 0.],
       [0., 5.]])

In [51]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[4., 5., 2.],
        [5., 2., 0.]]), array([[0.],
        [5.]]), array([[8., 9.],
        [7., 6.]])]

vsplit splits along the vertical axis, and array_split allows one to specify along which axis to split.